package com.huzzy.oauth_client.Scopces;

public enum FacebookScope {
    instagram_basic,
    instagram_manage_comments,
    instagram_manage_insights,
    publish_video,
    pages_messaging,
    pages_messaging_subscriptions,
    ads_management,
    ads_read,
    business_management,
    leads_retrieval,
    manage_pages,
    pages_manage_cta,
    pages_manage_instant_articles,
    pages_show_list,
    publish_pages,
    read_audience_network_insights,
    read_insights,
    read_page_mailboxes,
    groups_access_member_info,
    publish_to_groups,
    user_age_range,
    user_birthday,
    user_events,
    user_friends,
    user_gender,
    user_hometown,
    user_likes,
    user_link,
    user_location,
    user_photos,
    user_posts,
    user_tagged_places,
    user_videos;
 }
